---
# main configuration
cmdb_settings:
  cmdb_type: "servicenow"
  # cmdb_type: "freshworks"
  # cmdb_type: "bmc"
  cmdb_url: "https://dev78298.service-now.com/api/now/table/cmdb_ci"
  cmdb_token: ""
  cmdb_username: "admin"
  cmdb_password: "uxxrKp7KTS3Y"

nsg_settings:
  # nsg_url: "https://labdcbig3.netspyglass.com:9100"
  # nsg_token: "gVc1gpLpyroVzrze"
  nsg_url: "https://envoyproxy.netspyglass.com:10576" # "https://uct.netspyglass.com/" #"https://labdc.netspyglass.com:443"
  nsg_token: "Tju88nILa7eH1YFV" # "5eVJg3cXYgKltvQ1" #"JJcTKACMQFeIdXW3"
  nsg_channel: "v1public"
  netid: 1
  interval: 300
  skip_delete_non_cmdb_devices: True # This flag = True skips devices that are added in NSG directly

# netbox device attributes that should be used as filters for devices query.
# these translate directly into the return fields from the netbox json API.
# If no filter is specified, by default only devices with Active (1) status are pulled.
filters:
  status: [1, 3]
  manufacturer: ['juniper']
  custom_fields.field1: "foo"

# list of tags to filter devices in Netbox. Only devices that have this tag will be 
# synchronized to NetSpyGlass. Default is None, which causes all devices present in Netbox to be synchronized.
whitelist:
  - tag1
  - tag2

# list of tags to blacklist from netbox. Devices that have this tag will not be synchronized to NetSpyGlass.
# Blacklist filter is applied after the whitelist (if any). Default is None, which turns this off and causes all
# devices that pass whitelist will be synchronized
blacklist:
  - tagq

