# netbox device attributes that should be used as filters for devices query.
# these translate directly into the return fields from the netbox json API.
# If no filter is specified, by default only devices with Active (1) status are pulled.
filters:
  status: ["active", "staged", "offline"]
#  manufacturer: ['juniper']
#  custom_fields.field1: "foo"

# list of tags to filter devices in Netbox. Only devices that have this tag will be 
# synchronized to NetSpyGlass. Default is None, which causes all devices present in Netbox to be synchronized.
whitelist:
#  - tag1
#  - tag2

# list of tags to blacklist from netbox. Devices that have this tag will not be synchronized to NetSpyGlass.
# Blacklist filter is applied after the whitelist (if any). Default is None, which turns this off and causes all
# devices that pass whitelist will be synchronized
blacklist:
#  - tagq
# list of devices in nsg excluding from synchronization 
nsg_blacklist:
  name:
    - 192.168.1.251
    - 192.168.1.254
    - craig-dev3
    - cty1-bb01
    - cty1-bb02
    - cty1-dc01
    - cty1-dc02
    - cty1-pr01
    - cty99-bbbb
    - device-detail-2023
    - qa02-001
    - qa03-001
    - qa_test
    - test2
    - testzz
    - zqa-automation-new
  deviceId: 
    - 52
    - 53
    - 61
  address:
    - 0.0.0.1

default_channels: 
  v3ro:
    regexp: sjc12z.*|sjc12a-cr01|yyz1-bb02|sjc8-mt03|pdx3-dr01|sea2-pr01|pdx1-dc01
  v2ro:

domain: net.dropbox.com

# List of external nsg tags with corresponding netbox properties
nsgTags:
  DbxCluster:
    path: cluster
    transform: upper
  DbxContinent:
    path: continent
    transform: upper
  DbxFacility:
    path: facility
    transform: upper
  DbxMetro:
    path: metro
    transform: upper
  DbxMonitor:
    path: status.value
    transform: upper
    mapping:
      active: alerted
      "*": ignored
  DbxPod:
    path: config_context.pod 
  DbxRole:
    path: role.name
    transform: upper
  DbxSpine:
    path: config_context.spine
  DbxRack:
    path: rack.name
  DbxPortProfile:
    path: local_context_data.port_profile
  AirportCode:
    path: metro
    transform: upper
  GeoLatitude:
    path: latitude
  GeoLongitude:
    path: longitude
  Continent:
    path: site.name
    regexp: \b[a-zA-Z]{3}
    mapping: $metro_to_continent
    transform: upper
  Model:
    path: device_type.model
    transform: upper
  Vendor:
    path: device_type.manufacturer.name
  SerialNumber:
    path: serial
    transform: upper