ams: eu
arn: eu
atl: na
aus: na
bwi: na
cdg: eu
den: na
dfw: na
fra: eu
hhn: eu
hkg: ap
iad: na
jfk: na
lax: na
lgw: eu
lhr: eu
mad: eu
mia: na
mxp: eu
nrt: ap
nuq: na
ord: na
osl: eu
pdx: na
rhv: na
sea: na
sfo: na
sin: ap
sjc: na
syd: ap
tpe: ap
ttd: na
txl: eu
yyz: na
"*": unknown